export enum TesteEnum {
  IMAGEM_VAZIA = 'IMAGEM_VAZIA',
  THUMBNAIL = 'THUMBNAIL',
  PRINCIPAL_ITEM_CONJUNTO = 'PRINCIPAL_ITEM_CONJUNTO',
  MEDIA = 'MEDIA',
  PRINCIPAL = 'PRINCIPAL',
  ZOOM = 'ZOOM'
}
